// frontend/src/views/Login.vue
<!-- frontend/src/views/Login.vue -->
<template>
    <v-container class="fill-height" fluid>
      <v-row align="center" justify="center">
        <v-col cols="12" sm="8" md="4">
          <v-card>
            <v-card-title class="justify-center">
              <span class="text-h5">Login</span>
            </v-card-title>
            <v-card-text>
              <v-form @submit.prevent="doLogin">
                <v-text-field
                  v-model="username"
                  label="Username"
                  required
                ></v-text-field>
                <v-text-field
                  v-model="password"
                  label="Password"
                  type="password"
                  required
                ></v-text-field>
                <v-btn color="primary" type="submit" class="mt-4" block>
                  Login
                </v-btn>
              </v-form>
              <v-alert v-if="error" type="error" class="mt-4">
                {{ error }}
              </v-alert>
            </v-card-text>
          </v-card>
        </v-col>
      </v-row>
    </v-container>
  </template>
  
  <script>
  import api from '../api'
  
  export default {
    name: 'Login',
    data() {
      return {
        username: '',
        password: '',
        error: ''
      }
    },
    methods: {
      doLogin() {
        this.error = ''
        api.login(this.username, this.password)
          .then(res => {
            localStorage.setItem('token', res.data.token)
            this.$router.push('/dashboard/select-profile')
          })
          .catch(err => {
            this.error = err.response?.data?.error || 'Erro de login'
          })
      }
    }
  }
  </script>
  
  <style scoped>
  .fill-height {
    height: 100vh;
  }
  </style>

// frontend-react/src/views/Login.jsx
// frontend-react/src/views/Login.jsx
import React, { useState } from 'react';
import {
  Container,
  TextField,
  Button,
  Card,
  CardContent,
  Typography,
  Box,
} from '@mui/material';
import { useNavigate } from 'react-router-dom';
import api from '../api';
import { toast } from 'react-toastify';

function Login() {
  const navigate = useNavigate();
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);

  const handleLogin = async (e) => {
    e.preventDefault();
    setLoading(true);
    try {
      const response = await api.login(username, password);
      localStorage.setItem('token', response.data.token);
      navigate('/dashboard/select-profile');
      toast.success('Login realizado com sucesso!');
    } catch (error) {
      const errorMsg =
        error.response?.data?.error || 'Erro ao realizar login.';
      toast.error(errorMsg);
    } finally {
      setLoading(false);
    }
  };

  return (
    <Container maxWidth="sm" sx={{ mt: 8 }}>
      <Card>
        <CardContent>
          <Typography variant="h5" align="center" gutterBottom>
            Login
          </Typography>
          <Box component="form" onSubmit={handleLogin} noValidate>
            <TextField
              label="Username"
              variant="outlined"
              fullWidth
              margin="normal"
              required
              value={username}
              onChange={(e) => setUsername(e.target.value)}
            />
            <TextField
              label="Password"
              type="password"
              variant="outlined"
              fullWidth
              margin="normal"
              required
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
            <Button
              type="submit"
              variant="contained"
              color="primary"
              fullWidth
              disabled={loading}
              sx={{ mt: 2 }}
            >
              {loading ? 'Entrando...' : 'Login'}
            </Button>
          </Box>
        </CardContent>
      </Card>
    </Container>
  );
}

export default Login;
