// frontend-react/src/components/NavBar.jsx
// frontend-react/src/components/NavBar.jsx
import React from 'react';
import { AppBar, Toolbar, Box, Typography, Button } from '@mui/material';

import { useNavigate } from 'react-router-dom';

function NavBar() {
  const navigate = useNavigate();

  const handleNavigate = (route) => {
    navigate(`/dashboard/${route}`);
  };

  const handleLogout = () => {
    localStorage.removeItem('token');
    localStorage.removeItem('currentProfileId');
    navigate('/login');
  };

  return (
    <Box sx={{ flexGrow: 1, marginBottom: 2 }}>
      <AppBar position="static">
        <Toolbar>
          <Typography variant="h6" component="div" sx={{ flexGrow: 1 }}>
            Meu Site Saúde
          </Typography>
          <Button color="inherit" onClick={() => handleNavigate('select-profile')}>
            Mudar Perfil
          </Button>
          <Button color="inherit" onClick={() => handleNavigate('health-fever')}>
            Febre e Medicação
          </Button>
          <Button color="inherit" onClick={() => handleNavigate('health-diseases')}>
            Doenças
          </Button>
          <Button color="inherit" onClick={() => handleNavigate('health-reports')}>
            Relatórios
          </Button>
          <Button color="inherit" onClick={() => handleNavigate('management')}>
            Gestão
          </Button>
          <Button color="inherit" onClick={handleLogout}>
            Sair
          </Button>
        </Toolbar>
      </AppBar>
    </Box>
  );
}

export default NavBar;

// frontend/src/components/NavBar.vue
<!-- frontend/src/components/NavBar.vue -->
<template>
    <v-app-bar app color="primary" dark>
      <v-toolbar-title>Meu Site Saúde</v-toolbar-title>
      <v-spacer></v-spacer>
      <v-btn text @click="goTo('select-profile')">Mudar Perfil</v-btn>
      <v-btn text @click="goTo('health-fever')">Febre e Medicação</v-btn>
      <v-btn text @click="goTo('health-diseases')">Doenças</v-btn>
      <v-btn text @click="goTo('health-reports')">Relatórios</v-btn>
      <v-btn text @click="goTo('management')">Gestão</v-btn>
      <v-btn text @click="logout">Sair</v-btn>
    </v-app-bar>
  </template>
  
  <script>
  export default {
    name: 'NavBar',
    methods: {
      goTo(routeName) {
        this.$router.push(`/dashboard/${routeName}`)
      },
      logout() {
        localStorage.removeItem('token')
        this.$router.push('/login')
      }
    }
  }
  </script>
  
  <style scoped>
  /* Estilos adicionais se necessário */
  </style>
