// frontend/src/components/FeverMedicationChart.vue
<!-- frontend/src/components/FeverMedicationChart.vue -->
<template>
    <v-card>
      <v-card-title>Gráfico de Febre e Medicação</v-card-title>
      <v-card-text>
        <div v-if="chartOptions && series.length">
          <apexchart type="line" height="400" :options="chartOptions" :series="series"></apexchart>
        </div>
        <div v-else>
          <v-progress-circular indeterminate color="primary"></v-progress-circular>
        </div>
      </v-card-text>
    </v-card>
  </template>
  
  <script>
  import { defineComponent, ref, onMounted, watch } from 'vue'
  import ApexCharts from 'vue3-apexcharts'
  import api from '../api'
  
  export default defineComponent({
    name: 'FeverMedicationChart',
    components: {
      apexchart: ApexCharts
    },
    props: {
      startDate: {
        type: String,
        default: ''
      },
      endDate: {
        type: String,
        default: ''
      },
      diseaseID: {
        type: String,
        default: ''
      }
    },
    setup(props) {
      const series = ref([])
      const chartOptions = ref({})
  
      const fetchData = async () => {
        try {
          const params = {}
          if (props.startDate) params.start = props.startDate
          if (props.endDate) params.end = props.endDate
          if (props.diseaseID) params.disease_id = props.diseaseID
  
          const [recordsRes, medicationsRes, thresholdsRes] = await Promise.all([
            api.getFeverMedication(params),
            api.getMedications(),
            api.getFeverThresholds()
          ])
  
          const records = recordsRes.data
          const medications = medicationsRes.data
          const thresholds = thresholdsRes.data
  
          prepareChart(records, medications, thresholds)
        } catch (error) {
          this.$toast.error('Erro ao carregar dados do gráfico.')
          console.error('Erro ao carregar dados do gráfico:', error)
        }
      }
  
      const prepareChart = (records, medications, thresholds) => {
        if (records.length === 0) {
          series.value = []
          chartOptions.value = {}
          return
        }
  
        // Ordenar registros por data
        const sortedRecords = records.sort((a, b) => new Date(a.date_time) - new Date(b.date_time))
  
        // Preparar dados para febre (temperatura)
        const febreData = sortedRecords.map(r => ({
          x: new Date(r.date_time),
          y: r.temperature
        }))
  
        // Série para febre
        series.value = [
          {
            name: 'Temperatura',
            type: 'line',
            data: febreData
          }
        ]
  
        // Preparar anotações para medicações
        const medAnnotations = medications.map(med => ({
          x: med.date_time,
          borderColor: med.color,
          strokeDashArray: 0,
          label: {
            borderColor: med.color,
            style: {
              color: '#fff',
              background: med.color
            },
            text: med.name
          }
        }))
  
        // Preparar anotações para faixas de febre (bandas de fundo)
        const febreAnnotations = thresholds.map(threshold => ({
          y: threshold.min_temp,
          y2: threshold.max_temp,
          fillColor: threshold.color,
          opacity: 0.1,
          borderWidth: 0
        }))
  
        // Definir opções do gráfico
        chartOptions.value = {
          chart: {
            type: 'line',
            height: 400,
            toolbar: {
              show: true
            }
          },
          annotations: {
            xaxis: medAnnotations,
            yaxis: febreAnnotations
          },
          stroke: {
            width: [3],
            curve: 'straight'
          },
          xaxis: {
            type: 'datetime',
            title: {
              text: 'Data'
            }
          },
          yaxis: {
            title: {
              text: 'Temperatura (°C)'
            },
            min: 35,
            max: 42
          },
          tooltip: {
            shared: true,
            intersect: false,
            x: {
              format: 'dd/MM/yyyy HH:mm'
            }
          },
          markers: {
            size: 5
          },
          responsive: [
            {
              breakpoint: 600,
              options: {
                chart: {
                  height: 300
                },
                legend: {
                  position: 'bottom'
                }
              }
            }
          ],
          legend: {
            position: 'top',
            horizontalAlign: 'left'
          }
        }
      }
  
      onMounted(() => {
        fetchData()
      })
  
      watch(() => [props.startDate, props.endDate, props.diseaseID], () => {
        fetchData()
      })
  
      return {
        series,
        chartOptions
      }
    }
  })
  </script>
  
  <style scoped>
  /* Estilos adicionais se necessário */
  </style>

// frontend-react/src/components/FeverMedicationChart.jsx
// frontend-react/src/components/FeverMedicationChart.jsx
import React, { useEffect, useState } from 'react';
import ReactApexChart from 'react-apexcharts';
import api from '../api';
import { Box, CircularProgress, Typography } from '@mui/material';

function FeverMedicationChart({ startDate, endDate, diseaseID }) {
  const [series, setSeries] = useState([]);
  const [options, setOptions] = useState({});
  const [loading, setLoading] = useState(true);

  // Função para converter hex para RGBA, adicionando '#' se necessário
  const hexToRGBA = (hex, alpha) => {
    let r = 0, g = 0, b = 0;

    // Adicionar '#' se ausente
    if (!hex.startsWith('#')) {
      hex = `#${hex}`;
    }

    // 3 dígitos
    if (hex.length === 4) {
      r = parseInt(hex[1] + hex[1], 16);
      g = parseInt(hex[2] + hex[2], 16);
      b = parseInt(hex[3] + hex[3], 16);
    }
    // 6 dígitos
    else if (hex.length === 7) {
      r = parseInt(hex[1] + hex[2], 16);
      g = parseInt(hex[3] + hex[4], 16);
      b = parseInt(hex[5] + hex[6], 16);
    }

    return `rgba(${r},${g},${b},${alpha})`;
  };

  // Função para obter a cor da medicação com opacidade
  const getMedicationColor = (medName, medications) => {
    const med = medications.find((m) => m.name === medName);
    if (med && med.color) {
      const color = hexToRGBA(med.color, 0.8);
      console.log(`Medicação: ${medName}, Cor: ${color}`);
      return color;
    }
    return 'rgba(0,0,0,0.3)'; // Cor padrão com 30% de opacidade
  };

  const fetchData = async () => {
    setLoading(true);
    try {
      const params = {};
      if (startDate) params.start = startDate;
      if (endDate) params.end = endDate;
      if (diseaseID) params.disease_id = diseaseID;

      const [recordsRes, medicationsRes, thresholdsRes] = await Promise.all([
        api.getFeverMedication(params),
        api.getMedications(),
        api.getFeverThresholds(),
      ]);

      const records = recordsRes.data;
      const medications = medicationsRes.data;
      const thresholds = thresholdsRes.data;

      prepareChart(records, medications, thresholds);
    } catch (error) {
      console.error('Erro ao carregar dados do gráfico:', error);
    } finally {
      setLoading(false);
    }
  };

  const prepareChart = (records, medications, thresholds) => {
    if (records.length === 0) {
      setSeries([]);
      setOptions({});
      return;
    }

    // Ordenar registros por data/hora
    const sortedRecords = records.sort(
      (a, b) => new Date(a.date_time) - new Date(b.date_time)
    );

    // Filtrar registros com temperatura diferente de 0
    const filteredRecords = sortedRecords.filter(r => r.temperature !== 0);

    // Preparar dados para a temperatura
    const febreData = filteredRecords.map((r) => ({
      x: new Date(r.date_time).getTime(), // Timestamp em milissegundos
      y: r.temperature,
    }));

    // Série para temperatura
    const newSeries = [
      {
        name: 'Temperatura',
        type: 'line',
        data: febreData,
      },
    ];

    // Anotações para medicações
    const medAnnotations = sortedRecords
      .filter((r) => r.medication)
      .map((r) => ({
        x: new Date(r.date_time).getTime(),
        borderColor: getMedicationColor(r.medication, medications),
        strokeDashArray: 4, // Linha tracejada
        strokeWidth: 2, // Linha mais fina
        zIndex: 5, // Garantir que as anotações estejam abaixo da linha de temperatura
        label: {
          borderColor: getMedicationColor(r.medication, medications),
          style: {
            color: '#fff',
            background: getMedicationColor(r.medication, medications), // Cor com opacidade
          },
          text: r.medication,
          position: 'top', // Posicionar no topo para evitar sobreposição
          offsetY: -10, // Ajustar o offset para afastar do ponto
        },
      }));

    // Anotações para os limites de febre
    const febreAnnotations = thresholds.map((threshold) => ({
      y: threshold.min_temp,
      y2: threshold.max_temp,
      fillColor: hexToRGBA(threshold.color, 1.0), // Cor com baixa opacidade
      opacity: 0.1,
      borderWidth: 0,
    }));

    // Calcular os timestamps para min e max do eixo X
    const minTimestamp = new Date(startDate).setHours(0, 0, 0, 0);
    const maxTimestamp = new Date(endDate).setHours(23, 59, 59, 999); // Final do dia de endDate

    // Configuração das opções do gráfico
    setSeries(newSeries);
    setOptions({
      chart: {
        type: 'line',
        height: 400,
        toolbar: {
          show: true,
        },
      },
      annotations: {
        xaxis: medAnnotations,
        yaxis: febreAnnotations.map((ft) => ({
          y: ft.y,
          y2: ft.y2,
          fillColor: ft.fillColor,
          opacity: ft.opacity,
          borderWidth: ft.borderWidth,
          zIndex: 0, // Garantir que as anotações de febre estejam atrás das linhas
        })),
      },
      stroke: {
        width: [3],
        curve: 'straight',
      },
      xaxis: {
        type: 'datetime',
        title: {
          text: 'Data',
        },
        min: minTimestamp,
        max: maxTimestamp, // Agora inclui todo o dia de endDate
      },
      yaxis: {
        title: {
          text: 'Temperatura (°C)',
        },
        min: 35,
        max: 42,
      },
      tooltip: {
        shared: true,
        intersect: false,
        x: {
          format: 'dd/MM/yyyy HH:mm',
        },
      },
      markers: {
        size: 5,
      },
      responsive: [
        {
          breakpoint: 600,
          options: {
            chart: {
              height: 300,
            },
            legend: {
              position: 'bottom',
            },
          },
        },
      ],
      legend: {
        position: 'top',
        horizontalAlign: 'left',
      },
    });
  };

  useEffect(() => {
    fetchData();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [startDate, endDate, diseaseID]);

  if (loading) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" height="400px">
        <CircularProgress />
      </Box>
    );
  }

  if (!series.length) {
    return (
      <Box display="flex" justifyContent="center" alignItems="center" height="400px">
        <Typography variant="h6">Nenhum dado disponível para o gráfico.</Typography>
      </Box>
    );
  }

  return (
    <ReactApexChart options={options} series={series} type="line" height={400} />
  );
}

export default FeverMedicationChart;
